language: java
env:
  - ANDROID_HOME="./android-sdk-linux"

before_install:
  - bash android_install.sh

# TODO: Even using language: java, this fails on the first try, succeeds on second, please fix
script:
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport coveralls
