# We still need android to get the build tools/support libraries
language: android
android:
  components:
    - build-tools-21.1.1
    - android-21
    - extra-android-support

script:
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport coveralls
