language: java
env:
  - COMPONENTS="tools,platform-tools,build-tools-21.1.1,android-21,extra-android-m2repository,extra-android-support,extra-google-m2repository"

before_script:
  - ./android_install.sh $COMPONENTS

script:
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport coveralls
