# We still need android to get the build tools/support libraries
language: android
android:
  components:
    - tools
    - platform-tools
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
    - build-tools-21.1.1
    - android-21

before_script:
  - echo y | android update sdk -u

script:
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport coveralls
