language: android
android:
  components:
    - build-tools-21.0.2
    - sys-img-x86-android-19
    - android-19
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

env:
  matrix:
    - ANDROID_SDKS=android-19,sysimg-19 ANDROID_TARGET=android-19 ANDROID_ABI=x86

before_install:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

before_script:
  - sleep 60
  - bash ./wait_for_emulator
  - adb shell input keyevent 82 &

# Need to specify the bash command twice, for whatever reason, the first time fails
script:
  - bash gradlew connectedAndroidTestTestConfigDebug
  - bash gradlew connectedAndroidTestTestConfigDebug